# Kumihan-Formatter Branch Strategy Configuration
# Issue #1240: Development Process Normalization

# ブランチ戦略正規化設定
branch_strategy:
  # 作業期間制限
  work_duration:
    maximum_days: 7  # 1週間制限
    warning_days: 5  # 5日でアラート
    critical_days: 10  # 緊急レビュー対象
  
  # ブランチ命名規則
  naming_convention:
    pattern: "{type}/issue-{number}-{description}"
    allowed_types:
      - "feat"        # 新機能開発
      - "fix"         # バグ修正
      - "refactor"    # リファクタリング
      - "process"     # 開発プロセス改善
      - "docs"        # ドキュメント更新
      - "test"        # テスト追加・修正
      - "perf"        # パフォーマンス改善
      - "style"       # コードスタイル修正
    
    # 命名規則バリデーション
    validation:
      description_min_length: 3
      description_max_length: 50
      allowed_chars: "a-z0-9-"
      forbidden_words: ["temp", "tmp", "test123", "wip"]
  
  # 統合頻度管理
  integration:
    main_branch: "main"
    max_commits_before_integration: 20
    regular_integration_days: 3  # 3日ごとに統合推奨
  
  # ブランチ管理ルール
  management:
    # 自動削除対象
    auto_cleanup:
      merged_branches_after_days: 7
      stale_branches_after_days: 30
    
    # 保護ブランチ
    protected_branches:
      - "main"
      - "develop"
      - "release/*"
    
    # レビュー必須
    review_required:
      minimum_reviewers: 1
      require_code_owner_review: true
      dismiss_stale_reviews: true

# プロセス自動化
automation:
  # GitHub Actions統合
  github_actions:
    check_branch_naming: true
    monitor_branch_age: true
    enforce_integration_frequency: true
    auto_cleanup_merged_branches: true
  
  # 通知設定
  notifications:
    branch_age_warning: true
    naming_violation_alert: true
    integration_reminder: true
    cleanup_notification: true

# メトリクス収集
metrics:
  track_branch_duration: true
  track_integration_frequency: true
  track_naming_compliance: true
  generate_monthly_report: true

# 例外処理
exceptions:
  # 長期作業許可ケース
  long_term_work:
    allowed_types: ["refactor", "process"]
    max_duration_days: 14
    approval_required: true
  
  # 緊急対応
  hotfix:
    bypass_naming_check: true
    immediate_merge_allowed: true
    post_merge_documentation: true