# Claude System Behavior Override Configuration
# P7原則絶対遵守システム - 技術的強制実装
# Created: 2025-08-04 | Version: 2.0.0-strict

# 🚨 CRITICAL: システムレベル行動制御設定
system_override:
  name: "P7_SERENA_ABSOLUTE_ENFORCEMENT"
  priority: "CRITICAL_HIGHEST"
  bypass_allowed: false
  emergency_override: false

# 🛡️ ツール使用前検証システム
pre_execution_validation:
  enabled: true
  mode: "STRICT_BLOCK"  # STRICT_BLOCK | WARN_CONTINUE | LOG_ONLY

  # P7違反ツール絶対検出リスト
  forbidden_tools_strict:
    # ファイル操作系（serena必須）
    - "Edit"
    - "MultiEdit"
    - "Read"
    - "Write"
    - "LS"

    # コード検索・解析系（serena必須）
    - "Glob"
    - "Grep"
    - "Bash"  # 開発関連のbash使用時

    # 実行系（開発コンテキスト時）
    - "NotebookRead"
    - "NotebookEdit"

  # 例外許可条件（極めて限定的）
  exception_conditions:
    - condition: "git_operations"
      tools: ["Bash"]
      pattern: "^git\\s+"
      justification_required: true

    - condition: "simple_file_check"
      tools: ["Read", "LS"]
      context: "non_development"
      max_usage: 1
      justification_required: true

# 🔄 自動ツール置換システム
automatic_tool_replacement:
  enabled: true
  force_replacement: true
  log_replacements: true

  # 置換マッピング（従来ツール → serena）
  replacement_mapping:
    "Edit": "mcp__serena__replace_symbol_body"
    "MultiEdit": "mcp__serena__replace_symbol_body"
    "Read": "mcp__serena__find_symbol"
    "Write": "mcp__serena__insert_after_symbol"
    "Glob": "mcp__serena__search_for_pattern"
    "Grep": "mcp__serena__search_for_pattern"
    "LS": "mcp__serena__get_symbols_overview"

  # 置換時の自動パラメータ変換
  parameter_transformation:
    enabled: true
    smart_mapping: true
    preserve_intent: true

# 🚨 即座違反対応メカニズム
violation_response:
  # 第一段階：予防的警告
  pre_violation_warning:
    enabled: true
    message: "🚨 P7原則違反検出！serena-expertツール使用が絶対必須です"
    block_execution: true
    suggest_alternative: true

  # 第二段階：強制停止
  violation_detected:
    action: "IMMEDIATE_STOP"
    message: "⛔ P7原則違反により作業を強制停止します。serena-expertツールに切り替えてください"
    log_violation: true
    require_acknowledgment: true

  # 第三段階：自動是正
  auto_correction:
    enabled: true
    attempt_tool_swap: true
    preserve_user_intent: true
    notify_correction: true

# 🧠 心理的強化メカニズム
behavioral_conditioning:
  # 正しい行動の強化
  positive_reinforcement:
    serena_usage_praise: true
    success_feedback: "✅ serena-expert使用：P7原則完全遵守"
    progress_tracking: true

  # 違反行動の抑制
  negative_conditioning:
    violation_discomfort: true
    immediate_feedback: "❌ 従来ツール使用：P7原則違反"
    habit_interruption: true

  # 習慣形成支援
  habit_formation:
    repetition_rewards: true
    consistency_tracking: true
    milestone_celebrations: true

# 📊 監視・分析システム
monitoring_system:
  # リアルタイム監視
  real_time_tracking:
    tool_usage_monitoring: true
    pattern_detection: true
    anomaly_detection: true

  # 使用統計
  usage_analytics:
    serena_usage_rate: true
    violation_frequency: true
    compliance_score: true

  # レポート生成
  reporting:
    daily_compliance_report: true
    violation_trend_analysis: true
    improvement_suggestions: true

# 🔧 Serena統合最適化
serena_integration:
  # 必須初期化シーケンス
  initialization_sequence:
    - "mcp__serena__check_onboarding_performed"
    - "mcp__serena__get_current_config"
    - "mcp__serena__list_memories"

  # 推奨ワークフロー
  recommended_workflow:
    file_analysis: "mcp__serena__get_symbols_overview"
    symbol_search: "mcp__serena__find_symbol"
    code_editing: "mcp__serena__replace_symbol_body"
    pattern_search: "mcp__serena__search_for_pattern"
    insertion: "mcp__serena__insert_after_symbol"

  # パフォーマンス最適化
  optimization:
    token_efficiency: true
    batch_operations: true
    memory_utilization: true

# 🎯 コンテキスト識別システム
context_detection:
  # 開発コンテキスト識別
  development_context_triggers:
    - "コード"
    - "実装"
    - "開発"
    - "プログラム"
    - "ファイル"
    - "機能"
    - "バグ"
    - "修正"
    - "追加"
    - "変更"
    - "テスト"
    - "リファクタリング"

  # 非開発コンテキスト例外
  non_development_exceptions:
    - "質問"
    - "説明"
    - "理解"
    - "調査"
    - "分析のみ"

# 📈 学習・適応システム
adaptive_learning:
  # 使用パターン学習
  pattern_learning:
    enabled: true
    adapt_to_user_style: true
    optimize_suggestions: true

  # 改善提案
  improvement_suggestions:
    workflow_optimization: true
    efficiency_tips: true
    best_practices: true

# 🔐 セキュリティ設定
security:
  # 設定改変防止
  configuration_lock: true
  unauthorized_changes_block: true

  # ログ保護
  log_integrity: true
  tamper_detection: true

# 📅 メンテナンス設定
maintenance:
  auto_cleanup: true
  log_rotation: true
  performance_monitoring: true

  # 定期チェック
  health_checks:
    daily: true
    compliance_verification: true
    system_integrity: true

# 📋 メタデータ
metadata:
  version: "2.0.0-strict"
  created_date: "2025-08-04"
  created_by: "Claude Code P7 Enforcement System"
  purpose: "P7原則絶対遵守の技術的強制実装"
  compatibility: "CLAUDE.md v2.0+ required"

  # 更新履歴
  changelog:
    - "2.0.0-strict: 初期実装 - P7原則技術的強制システム"

  # 依存関係
  dependencies:
    - "CLAUDE.md P7原則"
    - ".claude-config.yml"
    - "serena-expert MCP tools"

# 🏁 起動時メッセージ
startup_message: |
  🚨 P7原則絶対遵守システム起動
  serena-expertツール強制使用モード有効
  従来ツール使用は即座に検出・是正されます

system_ready: true
