# Claude Code MCPåŠ¹çŽ‡åŒ–å°‚ç”¨è¨­å®šãƒ•ã‚¡ã‚¤ãƒ«
# Issue804 AIæœ€é©åŒ–ã‚·ã‚¹ãƒ†ãƒ çµ±åˆå¯¾å¿œ
# Phase B.4ã‚·ã‚¹ãƒ†ãƒ ï¼ˆ68.8%å‰Šæ¸›é”æˆï¼‰ã¨ã®å®Œå…¨çµ±åˆè¨­å®š

project_name: "Kumihan-Formatter"
config_type: "mcp_efficiency"
version: "1.0.0"
created: "2025-08-05"

# ðŸš€ MCPåŠ¹çŽ‡åŒ–ã‚³ã‚¢è¨­å®š
mcp_core:
  # åŸºæœ¬åŠ¹çŽ‡åŒ–è¨­å®š
  efficiency_mode: "ai_optimized"      # standard, optimized, ai_optimized
  target_reduction: 68.8               # Phase B.4ç›®æ¨™å‰Šæ¸›çŽ‡ï¼ˆ%ï¼‰
  auto_adjustment: true                # è‡ªå‹•èª¿æ•´æ©Ÿèƒ½

  # serenaãƒ„ãƒ¼ãƒ«æœ€é©åŒ–
  serena_optimization:
    # å‹•çš„ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿åˆ¶å¾¡
    dynamic_control:
      enabled: true
      ai_prediction: true              # AIäºˆæ¸¬é§†å‹•åˆ¶å¾¡
      context_awareness: true          # ã‚³ãƒ³ãƒ†ã‚­ã‚¹ãƒˆèªè­˜
      adaptive_scaling: true           # é©å¿œçš„ã‚¹ã‚±ãƒ¼ãƒªãƒ³ã‚°

    # ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿æœ€é©åŒ–è¨­å®š
    parameter_optimization:
      max_answer_chars:
        strategy: "ai_adaptive"        # fixed, adaptive, ai_adaptive
        base_value: 200000
        min_threshold: 50000
        max_threshold: 500000
        scaling_factor: 1.5
        ai_adjustment_rate: 0.2

      context_lines:
        before:
          base: 3
          ai_max: 15
          context_scaling: true
        after:
          base: 3
          ai_max: 15
          context_scaling: true

      search_optimization:
        smart_filtering: true
        result_ranking: true
        duplicate_elimination: true
        relevance_scoring: true

# ðŸ¤– AIçµ±åˆæœ€é©åŒ–
ai_integration:
  # Phase B.4ã‚·ã‚¹ãƒ†ãƒ çµ±åˆ
  phase_b4_integration:
    enabled: true
    prediction_engine: "kumihan_formatter.core.optimization.ai_optimization.prediction_engine"
    integration_manager: "kumihan_formatter.core.optimization.ai_optimization.ai_integration_manager"
    autonomous_controller: "kumihan_formatter.core.optimization.ai_optimization.autonomous_controller"

  # äºˆæ¸¬é§†å‹•æœ€é©åŒ–
  prediction_optimization:
    enabled: true
    prediction_accuracy_threshold: 85.0
    cache_predictions: true
    cache_duration: 3600              # 1æ™‚é–“

    # äºˆæ¸¬å¯¾è±¡æ“ä½œ
    predict_operations:
      - "find_symbol"
      - "search_for_pattern"
      - "get_symbols_overview"
      - "replace_symbol_body"
      - "insert_after_symbol"

    # äºˆæ¸¬ç‰¹å¾´é‡
    features:
      - "operation_type"
      - "content_size"
      - "context_complexity"
      - "recent_operations"
      - "user_patterns"

  # å­¦ç¿’ã‚·ã‚¹ãƒ†ãƒ çµ±åˆ
  learning_integration:
    online_learning: true
    model_update_frequency: "daily"    # hourly, daily, weekly
    feedback_collection: true
    performance_tracking: true

# ðŸ“Š åŠ¹æžœæ¸¬å®šãƒ»ç›£è¦–ã‚·ã‚¹ãƒ†ãƒ 
monitoring:
  # ãƒªã‚¢ãƒ«ã‚¿ã‚¤ãƒ ç›£è¦–
  real_time:
    enabled: true
    token_usage_tracking: true
    response_time_monitoring: true
    efficiency_calculation: true

  # åŠ¹æžœæ¸¬å®šæŒ‡æ¨™
  metrics:
    primary:
      - "token_reduction_rate"         # ä¸»è¦æŒ‡æ¨™ï¼šå‰Šæ¸›çŽ‡
      - "response_time"                # å¿œç­”æ™‚é–“
      - "prediction_accuracy"          # äºˆæ¸¬ç²¾åº¦

    secondary:
      - "cache_hit_rate"               # ã‚­ãƒ£ãƒƒã‚·ãƒ¥ãƒ’ãƒƒãƒˆçŽ‡
      - "operation_efficiency"         # æ“ä½œåŠ¹çŽ‡
      - "ai_intervention_rate"         # AIä»‹å…¥çŽ‡

  # ã‚¢ãƒ©ãƒ¼ãƒˆè¨­å®š
  alerts:
    efficiency_threshold: 60.0         # åŠ¹çŽ‡ä½Žä¸‹ã‚¢ãƒ©ãƒ¼ãƒˆé–¾å€¤ï¼ˆ%ï¼‰
    response_time_threshold: 5.0       # å¿œç­”æ™‚é–“ã‚¢ãƒ©ãƒ¼ãƒˆé–¾å€¤ï¼ˆç§’ï¼‰
    accuracy_threshold: 80.0           # ç²¾åº¦ä½Žä¸‹ã‚¢ãƒ©ãƒ¼ãƒˆé–¾å€¤ï¼ˆ%ï¼‰

  # ãƒ¬ãƒãƒ¼ãƒˆç”Ÿæˆ
  reporting:
    enabled: true
    frequency: "daily"                 # hourly, daily, weekly
    format: "json"                     # json, yaml, csv
    output_file: ".mcp-efficiency-report.json"

# ðŸ”§ è‡ªå‹•æœ€é©åŒ–æ©Ÿèƒ½
auto_optimization:
  # è‡ªå‹•èª¿æ•´æ©Ÿèƒ½
  auto_adjustment:
    enabled: true
    adjustment_strategy: "conservative" # conservative, balanced, aggressive
    min_adjustment_interval: 300       # 5åˆ†é–“éš”
    max_adjustment_per_hour: 10

  # æœ€é©åŒ–ãƒˆãƒªã‚¬ãƒ¼
  triggers:
    efficiency_drop:
      threshold: 5.0                   # 5%åŠ¹çŽ‡ä½Žä¸‹ã§ç™ºå‹•
      action: "parameter_adjustment"

    response_time_increase:
      threshold: 2.0                   # 2ç§’å¿œç­”æ™‚é–“å¢—ã§ç™ºå‹•
      action: "cache_optimization"

    prediction_accuracy_drop:
      threshold: 10.0                  # 10%ç²¾åº¦ä½Žä¸‹ã§ç™ºå‹•
      action: "model_retrain"

  # æœ€é©åŒ–æˆ¦ç•¥
  strategies:
    token_reduction:
      - "smart_filtering"
      - "context_compression"
      - "prediction_caching"
      - "batch_processing"

    response_optimization:
      - "parallel_processing"
      - "cache_warming"
      - "query_optimization"
      - "result_streaming"

# ðŸ›¡ï¸ ã‚¨ãƒ©ãƒ¼ãƒãƒ³ãƒ‰ãƒªãƒ³ã‚°ãƒ»ãƒ•ã‚©ãƒ¼ãƒ«ãƒãƒƒã‚¯
error_handling:
  # ãƒ•ã‚©ãƒ¼ãƒ«ãƒãƒƒã‚¯è¨­å®š
  fallback:
    enabled: true
    fallback_mode: "safe_default"      # safe_default, previous_config, manual
    recovery_attempts: 3
    recovery_timeout: 30               # 30ç§’

  # ã‚¨ãƒ©ãƒ¼åˆ†é¡žãƒ»å¯¾å¿œ
  error_responses:
    ai_system_error:
      action: "fallback_to_standard"
      log_level: "error"
      notification: true

    parameter_optimization_error:
      action: "reset_to_baseline"
      log_level: "warning"
      notification: false

    performance_degradation:
      action: "gradual_rollback"
      log_level: "warning"
      notification: true

  # å¾©æ—§æˆ¦ç•¥
  recovery:
    automatic_recovery: true
    health_check_interval: 60          # 1åˆ†é–“éš”
    recovery_validation: true
    performance_verification: true

# ðŸ“ ãƒ­ã‚°ãƒ»ãƒ‡ãƒãƒƒã‚°è¨­å®š
logging:
  # ãƒ­ã‚°ãƒ¬ãƒ™ãƒ«
  level: "info"                        # debug, info, warning, error

  # ãƒ­ã‚°å‡ºåŠ›
  outputs:
    - type: "file"
      path: ".mcp-efficiency.log"
      rotation: "daily"
      max_size: "10MB"

    - type: "console"
      enabled: false                   # æœ¬ç•ªã§ã¯ç„¡åŠ¹

  # ãƒ­ã‚°å†…å®¹
  log_components:
    - "efficiency_metrics"
    - "ai_predictions"
    - "parameter_adjustments"
    - "error_events"
    - "performance_data"

# ðŸš€ å°†æ¥æ‹¡å¼µè¨­å®š
future_extensions:
  # å®Ÿé¨“çš„æ©Ÿèƒ½
  experimental:
    enabled: false
    deep_learning_integration: false   # Deep Learningçµ±åˆï¼ˆå°†æ¥ï¼‰
    multi_model_ensemble: false        # ãƒžãƒ«ãƒãƒ¢ãƒ‡ãƒ«çµ±åˆï¼ˆå°†æ¥ï¼‰
    quantum_optimization: false        # é‡å­æœ€é©åŒ–ï¼ˆå°†æ¥ï¼‰

  # æ‹¡å¼µæ€§è¨­å®š
  extensibility:
    plugin_support: true
    custom_predictors: true
    external_ai_services: false        # å¤–éƒ¨AIã‚µãƒ¼ãƒ“ã‚¹çµ±åˆæº–å‚™
    api_integration: true

# è¨­å®šãƒ¡ã‚¿ãƒ‡ãƒ¼ã‚¿
metadata:
  config_version: "1.0.0"
  compatibility:
    claude_code_version: ">=1.0.0"
    python_version: ">=3.12"
    serena_version: ">=1.0.0"

  dependencies:
    - "kumihan_formatter.core.optimization.ai_optimization"
    - "kumihan_formatter.core.utilities.performance_metrics"

  last_modified: "2025-08-05T00:00:00Z"
  checksum: "auto_generated"
