# Claude Code AI統合設定ファイル
# Issue804 Phase B.4 AI最適化システム完全統合設定
# 68.8%削減達成システムとserenaツールの高度統合

project_name: "Kumihan-Formatter"
config_type: "ai_integration"
version: "1.0.0"
created: "2025-08-05"

# 🤖 AI最適化システム統合設定
ai_system:
  # Phase B.4システム設定
  phase_b4:
    enabled: true
    system_path: "kumihan_formatter.core.optimization.ai_optimization"
    integration_level: "full"           # basic, standard, full
    auto_initialization: true

  # コアAIコンポーネント
  core_components:
    ai_optimizer_core:
      enabled: true
      module: "ai_optimizer_core.AIOptimizerCore"
      priority: "high"

    prediction_engine:
      enabled: true
      module: "prediction_engine.PredictionEngine"
      accuracy_target: 85.0
      cache_enabled: true

    learning_system:
      enabled: true
      module: "learning_system.LearningSystem"
      online_learning: true
      update_frequency: "adaptive"

    autonomous_controller:
      enabled: true
      module: "autonomous_controller.AutonomousController"
      intervention_level: "moderate"    # minimal, moderate, aggressive

    ai_integration_manager:
      enabled: true
      module: "ai_integration_manager.AIIntegrationManager"
      coordination_mode: "smart"

# 🔗 serenaツール統合設定
serena_integration:
  # 統合レベル設定
  integration:
    level: "deep"                       # surface, standard, deep
    ai_enhancement: true
    predictive_optimization: true
    adaptive_parameters: true

  # AIエンハンスメント設定
  ai_enhancement:
    # ツール別最適化
    find_symbol:
      ai_prediction: true
      context_optimization: true
      result_ranking: true

    search_for_pattern:
      smart_filtering: true
      relevance_scoring: true
      duplicate_elimination: true

    get_symbols_overview:
      adaptive_depth: true
      context_aware_limits: true
      intelligent_summarization: true

    replace_symbol_body:
      change_prediction: true
      impact_analysis: true
      safety_validation: true

    insert_after_symbol:
      position_optimization: true
      context_analysis: true
      conflict_detection: true

  # パラメータ最適化設定
  parameter_optimization:
    # 動的調整システム
    dynamic_adjustment:
      enabled: true
      ai_driven: true
      context_aware: true
      performance_based: true

    # 具体的パラメータ設定
    parameters:
      max_answer_chars:
        optimization_strategy: "ai_adaptive"
        base_value: 200000
        ai_multiplier_range: [0.25, 2.5]
        context_scaling_factor: 1.2
        performance_threshold: 60.0

      depth:
        dynamic_adjustment: true
        context_based_max: 10
        ai_recommendation: true

      substring_matching:
        ai_suggestion: true
        context_optimization: true

      include_body:
        smart_decision: true
        size_aware: true
        relevance_based: true

# 🧠 機械学習・予測システム
ml_prediction:
  # 予測エンジン設定
  prediction_engine:
    # 予測対象
    targets:
      operation_efficiency: true
      parameter_optimization: true
      result_relevance: true
      response_time: true

    # 予測モデル設定
    models:
      efficiency_predictor:
        type: "lightgbm"
        features: ["operation_type", "context_size", "history_pattern"]
        accuracy_target: 85.0

      parameter_optimizer:
        type: "xgboost"
        features: ["content_complexity", "user_pattern", "performance_history"]
        optimization_target: "token_efficiency"

      relevance_scorer:
        type: "neural_network"
        features: ["semantic_similarity", "context_relevance", "user_intent"]
        enabled: false                  # 将来実装予定

  # 学習システム設定
  learning_system:
    # オンライン学習
    online_learning:
      enabled: true
      learning_rate: 0.01
      batch_size: 32
      update_frequency: "hourly"

    # データ収集
    data_collection:
      operation_logs: true
      performance_metrics: true
      user_feedback: true
      system_responses: true

    # モデル管理
    model_management:
      version_control: true
      a_b_testing: true
      rollback_capability: true
      performance_monitoring: true

# 📊 効果測定・監視システム
monitoring_integration:
  # リアルタイム監視
  real_time_monitoring:
    enabled: true
    metrics_collection: "continuous"
    performance_tracking: true
    anomaly_detection: true

  # 効果測定指標
  metrics:
    # 主要効果指標
    primary_metrics:
      token_reduction_rate:
        target: 68.8
        measurement_frequency: "per_operation"
        alert_threshold: 60.0

      prediction_accuracy:
        target: 85.0
        measurement_frequency: "continuous"
        alert_threshold: 80.0

      response_time_improvement:
        target: 2.0                     # 秒以下
        measurement_frequency: "per_operation"
        alert_threshold: 5.0

    # 副次効果指標
    secondary_metrics:
      ai_intervention_success_rate:
        target: 90.0
        measurement_frequency: "hourly"

      cache_hit_rate:
        target: 70.0
        measurement_frequency: "continuous"

      user_satisfaction_score:
        target: 8.0                     # 10点満点
        measurement_frequency: "daily"

  # アラート・通知システム
  alerting:
    # アラート設定
    alerts:
      performance_degradation:
        threshold: 10.0                 # 10%性能低下
        action: "auto_adjustment"
        notification: true

      ai_system_error:
        threshold: "any_error"
        action: "fallback_mode"
        notification: true

      efficiency_target_miss:
        threshold: 5.0                  # 目標から5%以上乖離
        action: "parameter_adjustment"
        notification: false

    # 通知設定
    notifications:
      channels: ["log", "file"]         # log, file, email, slack
      severity_levels: ["error", "warning"]
      frequency_limit: "5_per_hour"

# 🔧 自動最適化・適応システム
auto_optimization:
  # 自動最適化設定
  optimization:
    enabled: true
    optimization_level: "moderate"     # minimal, moderate, aggressive
    learning_enabled: true

  # 適応システム
  adaptation:
    # 環境適応
    environment_adaptation:
      enabled: true
      context_learning: true
      usage_pattern_recognition: true
      performance_optimization: true

    # パラメータ適応
    parameter_adaptation:
      enabled: true
      ai_driven_adjustment: true
      performance_based_tuning: true
      user_preference_learning: true

    # 戦略適応
    strategy_adaptation:
      enabled: true
      multi_strategy_testing: true
      best_strategy_selection: true
      continuous_improvement: true

  # 自動調整トリガー
  triggers:
    performance_triggers:
      efficiency_drop: 5.0              # 5%効率低下
      response_time_increase: 2.0       # 2秒応答時間増
      error_rate_increase: 10.0         # 10%エラー率増

    learning_triggers:
      new_data_threshold: 100           # 100新規データで学習開始
      accuracy_drop: 5.0                # 5%精度低下で再学習
      model_staleness: 24               # 24時間でモデル更新検討

# 🛡️ 安全性・信頼性設定
safety_reliability:
  # 安全性設定
  safety:
    # フォールバック機能
    fallback:
      enabled: true
      trigger_conditions:
        - "ai_system_failure"
        - "performance_degradation_severe"
        - "prediction_accuracy_critical"
      fallback_mode: "traditional_serena"
      recovery_validation: true

    # 制限・制約
    constraints:
      max_parameter_change: 50.0        # 最大50%パラメータ変更
      min_efficiency_threshold: 50.0    # 最低50%効率維持
      max_response_time: 10.0           # 最大10秒応答時間

    # 検証システム
    validation:
      pre_optimization_check: true
      post_optimization_validation: true
      rollback_on_failure: true

  # 信頼性設定
  reliability:
    # 冗長性
    redundancy:
      backup_systems: true
      multiple_prediction_models: true
      fallback_configurations: true

    # 復旧システム
    recovery:
      automatic_recovery: true
      health_check_frequency: 60        # 60秒間隔
      recovery_attempts: 3
      escalation_procedures: true

# 🔍 デバッグ・開発支援
development_support:
  # デバッグ設定
  debugging:
    enabled: false                      # 本番では無効
    verbose_logging: false
    operation_tracing: false
    performance_profiling: false

  # 開発支援機能
  development_features:
    configuration_validation: true
    parameter_suggestions: true
    optimization_recommendations: true
    performance_insights: true

  # テスト支援
  testing_support:
    test_mode: false
    mock_ai_responses: false
    performance_simulation: false
    stress_testing: false

# 📋 設定メタデータ・互換性
metadata:
  # バージョン情報
  version_info:
    config_version: "1.0.0"
    ai_system_version: "Phase_B4_v1.0"
    serena_compatibility: ">=1.0.0"
    claude_code_compatibility: ">=1.0.0"

  # 依存関係
  dependencies:
    required:
      - "kumihan_formatter.core.optimization.ai_optimization"
      - "kumihan_formatter.core.utilities.performance_metrics"
    optional:
      - "numpy>=1.21.0"
      - "scikit-learn>=1.0.0"
      - "lightgbm>=3.0.0"
      - "xgboost>=1.5.0"

  # 設定検証
  validation:
    schema_version: "1.0.0"
    last_validated: "2025-08-05T00:00:00Z"
    validation_checksum: "auto_generated"

  # 更新履歴
  changelog:
    - version: "1.0.0"
      date: "2025-08-05"
      changes:
        - "初期AI統合設定実装"
        - "Phase B.4システム完全統合"
        - "serenaツール高度統合"
        - "68.8%削減効果対応設定"
