# Kumihan-Formatter プロジェクト クリーンアップ設定
# ファイル整理・自動管理システム設定ファイル

# 基本設定
settings:
  # ドライランモード（確認のみ、削除しない）
  dry_run: false

  # 対話モード（各ファイルの削除前に確認）
  interactive: false

  # 自動モード（確認なしで削除実行）
  auto: false

  # 詳細ログ出力
  verbose: true

  # 統計情報表示
  show_stats: true

# セーフモード設定
safety:
  # 作成から何日以内のファイルは削除しない
  min_age_days: 0

  # サイズが大きすぎるファイルは確認
  max_size_mb: 100

  # バックアップ作成（削除前にコピー）
  create_backup: false
  backup_dir: ".backup"

# 削除対象パターン
patterns:
  # 大容量テストファイル
  large_test_files:
    - "*k_test_file.*"
    - "*mb_test_file.*"
    - "*gb_test_file.*"
    - "large_test_*"
    - "huge_test_*"
    - "massive_test_*"
    - "benchmark_test_*"

  # レポートファイル
  report_files:
    - "*_report_*.json"
    - "*_report_*.md"
    - "*_report_*.txt"
    - "*_report_*.html"
    - "*_報告書_*.md"
    - "*_Final_Report.*"
    - "Issue_*_Complete_*.md"
    - "behavioral_control_*.json"
    - "p7_compliance_*.json"
    - "token-usage-report.*"

  # 一時実行ファイル
  temp_files:
    - "temp_*"
    - "tmp_*"
    - "test_temp_*"
    - "temp_test_*"
    - "test_output_*"
    - "performance_test_*"
    - "benchmark_output_*"
    - "debug_output_*"

  # プロファイリングファイル
  profiling_files:
    - "*.prof"
    - "*.cprof"
    - "profiling_*"
    - "memory_profile_*"

  # ログファイル
  log_files:
    - "*.log"
    - "debug.log"
    - "error.log"
    - "test.log"

  # キャッシュファイル
  cache_files:
    - "cache_*"
    - "*.cache"

  # バックアップファイル
  backup_files:
    - "*.bak"
    - "*.backup"
    - "*~"
    - "backup_*"

  # システムファイル
  system_files:
    - ".DS_Store"
    - ".DS_Store?"
    - "._*"
    - "Thumbs.db"
    - "ehthumbs.db"

# 除外パターン（削除対象から除外）
exclude_patterns:
  # 重要なシステムファイル
  - "CLAUDE.md"
  - "README.md"
  - "LICENSE"
  - "CHANGELOG.md"
  - "CONTRIBUTING.md"
  - "pyproject.toml"
  - "Makefile"
  - ".gitignore"
  - ".pre-commit-config.yaml"
  - ".flake8"

  # 設定ファイル
  - "*.yml"
  - "*.yaml"
  - "*.json"
  - "*.toml"
  - "*.ini"
  - "*.cfg"

  # 重要なディレクトリ
  - "kumihan_formatter/"
  - "tests/unit/"
  - "tests/integration/"
  - "tests/performance/"
  - "scripts/"
  - "docs/"
  - ".github/"
  - ".venv*/"
  - "venv*/"

# 除外ディレクトリ（スキャン対象から除外）
exclude_directories:
  - ".git"
  - ".venv"
  - ".venv312"
  - "venv"
  - "__pycache__"
  - ".pytest_cache"
  - "htmlcov"
  - "dist"
  - "build"
  - "*.egg-info"
  - "node_modules"

# tmp/配下強制ルール設定
tmp_rule:
  # tmp/配下強制ルールを有効にする
  enabled: true

  # 違反時の処理
  violation_action: "warn"  # warn, move, delete

  # 警告メッセージ表示
  show_warnings: true

  # ログ記録
  log_violations: true
  log_file: "tmp_rule_violations.log"

  # 一時ファイルパターン
  temp_file_patterns:
    - "temp_*"
    - "tmp_*"
    - "*_temp.*"
    - "*_tmp.*"
    - "test_output_*"
    - "debug_*"
    - "performance_*"
    - "benchmark_*"
    - "profile_*"
    - "trace_*"
    - "dump_*"
    - "cache_*"
    - "*.cache"
    - "*.prof"
    - "*.log"
    - "output_*"
    - "result_*"
    - "export_*"
    - "convert_*"
    - "generated_*"
    - "auto_*"
    - "sample_output*"

# ログ設定
logging:
  # ログレベル（DEBUG, INFO, WARNING, ERROR）
  level: "INFO"

  # ログファイル出力
  to_file: false
  log_file: "cleanup.log"

  # コンソール出力
  to_console: true

  # 日本語メッセージ
  japanese: true

# 統計設定
statistics:
  # 統計情報収集
  collect: true

  # 統計ファイル出力
  save_to_file: false
  stats_file: "cleanup_stats.json"

  # 表示項目
  show_file_count: true
  show_total_size: true
  show_category_breakdown: true
  show_time_taken: true
