[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kumihan-formatter"
version = "0.9.0-alpha.8"
description = "CoC6th同人シナリオなどのテキストファイルをワンコマンドで配布可能なHTMLに自動組版するCLIツール"
authors = [{name = "mo9mo9-uwu-mo9mo9"}]
readme = "README.md"
requires-python = ">=3.12"
license = {text = "Proprietary"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: Other/Proprietary License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "click>=8.0",
    "jinja2>=3.0",
    "rich>=13.0",
    "watchdog>=3.0",
    "pyyaml>=6.0",
    "pydantic>=2.0",
]

[project.scripts]
kumihan = "kumihan_formatter.cli:main"

[project.optional-dependencies]
dev = [
    "black>=23.0",
    "isort>=5.0",
    "flake8>=6.0",
    "beautifulsoup4>=4.9",
    "psutil>=5.9",
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "pytest-timeout>=2.0",
    "pytest-xdist>=3.5.0",
    "mypy>=1.0",
    "types-psutil",
    "types-PyYAML",
]

[tool.setuptools.packages.find]
exclude = ["dev*", "tests*", "tools*"]

[tool.setuptools.package-data]
kumihan_formatter = [
    "templates/*.html.j2",
    "templates/*.css",
    "templates/*.js",
    "templates/partials/*",
    "assets/*",
    "config/*.py",
    "models/*.py"
]


[tool.black]
line-length = 88
target-version = ['py312']

[tool.pytest.ini_options]
testpaths = ["tests"]
collect_ignore = [
    "kumihan_formatter/commands/test_file_command.py",
    "scripts/test_guard.py",
]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
minversion = "6.0"
addopts = [
    "-v",
    "--strict-markers",
    "--tb=short",
    "--cov=kumihan_formatter",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-report=xml",
    "--cov-fail-under=6",
    "--durations=10",
    "--maxfail=5",
    "-x",
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
    "ignore::UserWarning:tkinter.*",
    "ignore::RuntimeWarning:.*",
]
markers = [
    "unit: Unit tests - fast, isolated tests",
    "integration: Integration tests - tests component interactions",
    "e2e: End-to-end tests - full system tests",
    "slow: Slow running tests (>1s)",
    "performance: Performance benchmark tests",
    "gui: GUI-related tests requiring display",
    "skip_ci: Tests to skip in CI environment",
]
timeout = 300
log_cli = false
log_cli_level = "WARNING"
# 並行実行設定 (pytest-xdist が利用可能な場合)
# addopts に "-n auto" を追加することで並行実行可能

[tool.coverage.run]
source = ["kumihan_formatter"]
omit = [
    "*/tests/*",
    "*/test_*",
    "*/__pycache__/*",
    "*/migrations/*",
    "*/venv/*",
    "*/.venv/*",
    "*/site-packages/*",
]
branch = true
parallel = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if False:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
    "except ImportError:",
    "except ModuleNotFoundError:",
    "# TYPE_CHECKING",
    "if TYPE_CHECKING:",
]
fail_under = 0
precision = 2
show_missing = true
skip_covered = false

[tool.coverage.html]
directory = "htmlcov"

[tool.coverage.xml]
output = "coverage.xml"

[tool.isort]
profile = "black"
line_length = 88

# バージョン管理設定
[tool.bumpversion]
current_version = "0.3.0-alpha.1"
commit = true
tag = true
tag_name = "v{new_version}"
message = "release: bump version to {new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "kumihan_formatter/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

# mypy設定
[tool.mypy]
strict = true
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
exclude = ["dist/**/*"]
