"""ファイル操作UI プロトコル定義

循環依存を避けるためのプロトコル定義モジュール。
"""

from typing import Protocol


class UIProtocol(Protocol):
    """UI interface protocol to avoid circular dependency"""

    def warning(self, message: str, details: str | None = None) -> None: ...

    def file_copied(self, count: int) -> None: ...

    def files_missing(self, files: list[str]) -> None: ...

    def duplicate_files(self, duplicates: dict[str, int]) -> None: ...

    def info(self, message: str, details: str | None = None) -> None: ...

    def hint(self, message: str, details: str | None = None) -> None: ...

    def file_error(self, file_path: str, message: str) -> None: ...

    def encoding_error(self, file_path: str) -> None: ...

    def permission_error(self, error: str) -> None: ...

    def unexpected_error(self, error: str) -> None: ...
