# TDD Security Test Configuration
# Issue #640 改善対応: セキュリティテストの精度向上・設定外部化

# セキュリティパターン設定
security_patterns:
  sql_injection:
    # 危険なパターン
    dangerous_patterns:
      - "SELECT\\s+.*\\s+FROM\\s+.*\\s+WHERE\\s+.*\\+"
      - "\\.execute\\([^)]*%[^)]*\\)"
      - "f\".*SELECT.*{.*}.*\""
      - "\".*'\\s*\\+\\s*.*\\+\\s*'\""
    # セキュアなパターン（ホワイトリスト）
    safe_patterns:
      - "\\.execute\\([\"'].*\\?.*[\"']"
      - "PreparedStatement"
      - "cursor\\.execute\\([^,]+,\\s*\\("
      - "connection\\.execute\\(text\\("
  
  xss_protection:
    dangerous_patterns:
      - "\\.write\\([^)]*\\+[^)]*\\)"
      - "f\"<.*{.*}.*>\""
      - "\"<.*\"\\s*\\+\\s*.*\\+\\s*\".*>\""
      - "render_template\\([^)]*\\+[^)]*\\)"
    safe_patterns:
      - "escape\\("
      - "html\\.escape\\("
      - "\\|safe"
      - "Markup\\("

# タイムアウト設定
timeouts:
  base_timeout: 60
  per_test_factor: 2
  maximum_timeout: 600
  minimum_timeout: 30

# カバレッジ目標設定
coverage_targets:
  critical: 90
  important: 80
  supportive: 60
  special: 40

# 国際化メッセージ設定
messages:
  ja:
    sql_injection_found: "潜在的なSQLインジェクション脆弱性を{count}件発見"
    xss_vulnerability_found: "潜在的なXSS脆弱性を{count}件発見"
    no_vulnerabilities: "脆弱性は検出されませんでした"
    test_execution_error: "テスト実行エラー: {error}"
  en:
    sql_injection_found: "Found {count} potential SQL injection vulnerabilities"
    xss_vulnerability_found: "Found {count} potential XSS vulnerabilities"
    no_vulnerabilities: "No vulnerabilities detected"
    test_execution_error: "Test execution error: {error}"

# 除外設定
exclusions:
  # 除外するファイルパターン
  file_patterns:
    - "*/test_*"
    - "*/tests/*"
    - "*/__pycache__/*"
    - "*/migrations/*"
  # 除外するディレクトリ
  directories:
    - ".git"
    - "__pycache__"
    - ".pytest_cache"
    - "htmlcov"